"""unique key

Revision ID: 10
Revises: 9
Create Date: 2021-08-20 02:09:40.277401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10'
down_revision = '9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_auxInfoFields_org_id'), 'auxInfoFields', ['org_id', 'prompt'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_auxInfoFields_org_id'), 'auxInfoFields', type_='unique')
    # ### end Alembic commands ###
