"""add

Revision ID: 11
Revises: 10
Create Date: 2021-08-20 18:22:19.831983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11'
down_revision = '10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaxRecordScan', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_vaxRecordScan_type_id_vaxRecordType'), 'vaxRecordScan', 'vaxRecordType', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vaxRecordScan_type_id_vaxRecordType'), 'vaxRecordScan', type_='foreignkey')
    op.drop_column('vaxRecordScan', 'type_id')
    # ### end Alembic commands ###
