"""empty message

Revision ID: 8e81bed2a85a
Revises: 11
Create Date: 2021-09-04 19:01:47.756039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12'
down_revision = '11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_org_id_orgs'), 'user', 'orgs', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_org_id_orgs'), 'user', type_='foreignkey')
    # ### end Alembic commands ###
