"""empty message

Revision ID: 238850e991c9
Revises: 12
Create Date: 2021-09-05 18:16:48.786033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13'
down_revision = '12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smsRecords', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('smsRecords', sa.Column('swab_result_id', sa.Integer(), nullable=True))
    op.add_column('smsRecords', sa.Column('phone', sa.String(length=100), nullable=False))
    op.add_column('smsRecords', sa.Column('notification_type', sa.Integer(), nullable=True))
    op.drop_constraint('fk_smsRecords_org_id_orgs', 'smsRecords', type_='foreignkey')
    op.create_foreign_key(op.f('fk_smsRecords_swab_result_id_swabResult'), 'smsRecords', 'swabResult', ['swab_result_id'], ['id'])
    op.drop_column('smsRecords', 'org_id')
    op.drop_column('smsRecords', 'test_collected_at')
    op.drop_column('smsRecords', 'pid')
    op.add_column('swabResult', sa.Column('sms_sent', sa.Boolean(), nullable=True))
    op.add_column('swabResult', sa.Column('fname', sa.String(length=100), nullable=True))
    op.add_column('swabResult', sa.Column('lname', sa.String(length=100), nullable=True))
    op.add_column('swabResult', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('swabResult', sa.Column('sex', sa.String(length=100), nullable=True))
    op.add_column('swabResult', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('swabResult', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('swabResult', sa.Column('collection_datetime', sa.DateTime(), nullable=True))
    op.add_column('swabResult', sa.Column('result', sa.String(length=100), nullable=True))
    op.add_column('swabs', sa.Column('pdf_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swabs', 'pdf_sent')
    op.drop_column('swabResult', 'sms_sent')
    op.drop_column('swabResult', 'fname')
    op.drop_column('swabResult', 'lname')
    op.drop_column('swabResult', 'dob')
    op.drop_column('swabResult', 'sex')
    op.drop_column('swabResult', 'phone')
    op.drop_column('swabResult', 'email')
    op.drop_column('swabResult', 'collection_datetime')
    op.drop_column('swabResult', 'result')
    op.add_column('smsRecords', sa.Column('pid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('smsRecords', sa.Column('test_collected_at', mysql.DATETIME(), nullable=True))
    op.add_column('smsRecords', sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_smsRecords_swab_result_id_swabResult'), 'smsRecords', type_='foreignkey')
    op.create_foreign_key('fk_smsRecords_org_id_orgs', 'smsRecords', 'orgs', ['org_id'], ['id'])
    op.drop_column('smsRecords', 'notification_type')
    op.drop_column('smsRecords', 'phone')
    op.drop_column('smsRecords', 'swab_result_id')
    op.drop_column('smsRecords', 'sent_at')
    # ### end Alembic commands ###
