"""empty message

Revision ID: 89085c6a9720
Revises: 16
Create Date: 2021-09-15 16:51:14.142921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17'
down_revision = '16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auxInfoFields', sa.Column('label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auxInfoFields', 'label')
    # ### end Alembic commands ###
