"""add AuxInfoFields is_hidden

Revision ID: 18
Revises: 17
Create Date: 2021-10-01 09:24:18.112412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18'
down_revision = '17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auxInfoFields', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auxInfoFields', 'is_hidden')
    # ### end Alembic commands ###
