"""empty message

Revision ID: 16b1fabeeaee
Revises: 18
Create Date: 2021-10-01 18:51:24.198814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19'
down_revision = '18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swabResult', sa.Column('laboratory', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swabResult', 'laboratory')
    # ### end Alembic commands ###
