"""1-UsersAuxInfoData

Revision ID: 1
Revises: 0
Create Date: 2021-08-13 01:46:22.330315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = '0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersAuxInfoData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['auxInfoFields.id'], name=op.f('fk_usersAuxInfoData_field_id_auxInfoFields')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_usersAuxInfoData_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usersAuxInfoData'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersAuxInfoData')
    # ### end Alembic commands ###
