"""empty message

Revision ID: 84f369ff07aa
Revises: 20
Create Date: 2021-10-10 01:50:24.226305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21'
down_revision = '20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swabResult', 'swab_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('swabResult', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('swabResult', 'org_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swabResult', 'org_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('swabResult', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('swabResult', 'swab_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
