"""empty message

Revision ID: a079431c6881
Revises: 2
Create Date: 2021-08-13 17:57:05.641939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersVaccinationInfo')
    op.drop_index('uq_auxInfoFields_org_id', table_name='auxInfoFields')
    op.create_foreign_key(op.f('fk_auxInfoFields_org_id_orgs'), 'auxInfoFields', 'orgs', ['org_id'], ['id'])
    op.add_column('user', sa.Column('email_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('sms_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('agree_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registration_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_user_registration_id'), 'user', ['registration_id'])
    op.drop_column('user', 'title')
    op.drop_column('usersTestingInfo', 'phone')
    op.add_column('vaxRecordData', sa.Column('clinic_site', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaxRecordData', 'clinic_site')
    op.add_column('usersTestingInfo', sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('user', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(op.f('uq_user_registration_id'), 'user', type_='unique')
    op.drop_column('user', 'registration_id')
    op.drop_column('user', 'agree_at')
    op.drop_column('user', 'sms_notification')
    op.drop_column('user', 'email_notification')
    op.drop_constraint(op.f('fk_auxInfoFields_org_id_orgs'), 'auxInfoFields', type_='foreignkey')
    op.create_index('uq_auxInfoFields_org_id', 'auxInfoFields', ['org_id', 'prompt'], unique=False)
    op.create_table('usersVaccinationInfo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('employee_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('email_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sms_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('agree_at', mysql.DATETIME(), nullable=True),
    sa.Column('other_info', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`email_notification` in (0,1))', name='ck_usersVaccinationInfo_email_notification'),
    sa.CheckConstraint('(`sms_notification` in (0,1))', name='ck_usersVaccinationInfo_sms_notification'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='fk_usersVaccinationInfo_org_id_orgs'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_usersVaccinationInfo_user_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
