"""empty message

Revision ID: 5648ec46c062
Revises: 3
Create Date: 2021-08-14 07:27:43.554954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4'
down_revision = '3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersTestingInfo', sa.Column('op_group_setting', sa.Boolean(), nullable=True))
    op.add_column('usersTestingInfo', sa.Column('op_prescribed_test', sa.Boolean(), nullable=True))
    op.add_column('usersTestingInfo', sa.Column('op_covid_symptoms', sa.Boolean(), nullable=True))
    op.add_column('usersTestingInfo', sa.Column('op_exposure', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersTestingInfo', 'op_exposure')
    op.drop_column('usersTestingInfo', 'op_covid_symptoms')
    op.drop_column('usersTestingInfo', 'op_prescribed_test')
    op.drop_column('usersTestingInfo', 'op_group_setting')
    # ### end Alembic commands ###
