"""remove step

Revision ID: 5
Revises: 4
Create Date: 2021-08-18 01:29:34.886802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5'
down_revision = '4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auxInfoFields', 'step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auxInfoFields', sa.Column('step', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    # ### end Alembic commands ###
