"""administered_at

Revision ID: 6
Revises: 5
Create Date: 2021-08-18 02:51:21.164422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6'
down_revision = '5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaxRecordData', sa.Column('administered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaxRecordData', 'administered_at')
    # ### end Alembic commands ###
